name: scroll_to_specific_widget
description: Allows conditional scrolling to specific widgets within a scrollable viewport
version: 1.0.0
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  outcome_types:
    git:
      url: git@github.com:ezee-GmbH/outcome_types.git
      ref: master
  provider: ^6.1.2

dev_dependencies:
  very_good_analysis: ^6.0.0
